
--1)
SELECT A.[CODIGO]
, A.[NOMBRE]
, A.[Nacionalidad]
, COUNT(AL.CODIGO_LIBRO) AS CANTIDAD_LIBROS
FROM [BIBLIOTECA].[AUTOR] AS A
		JOIN [BIBLIOTECA].[AUTOR_LIBRO] AS AL
			ON A.CODIGO=AL.CODIGO_AUTOR
GROUP BY A.CODIGO , A.[NOMBRE], A.[Nacionalidad]
HAVING COUNT(*)>1;

--2)
SELECT  [NOMBRE], [edad]
FROM [BIBLIOTECA].[USUARIO]

--3)
SELECT  [NOMBRE], [edad]
FROM [BIBLIOTECA].[USUARIO] AS U
WHERE U.CARRERA = 'Informatica'

--4)
SELECT  [NOMBRE], APELLIDOS
FROM [BIBLIOTECA].[USUARIO] AS U
WHERE U.APELLIDOS like 'g%'

--5)
SELECT NOMBRE
FROM BIBLIOTECA.AUTOR AS A
	JOIN BIBLIOTECA.AUTOR_LIBRO AS AL
		ON A.CODIGO = AL.CODIGO_AUTOR
			JOIN BIBLIOTECA.LIBRO AS L
				ON AL.CODIGO_LIBRO = L.CODIGO_LIBRO
WHERE L.TITULO = 'Visual Studio Net'

--6)
SELECT NOMBRE , NACIONALIDAD
FROM BIBLIOTECA.AUTOR
WHERE (Nacionalidad='Frances' OR Nacionalidad= 'USA')

--7)
SELECT TITULO, AREA
FROM BIBLIOTECA.LIBRO
WHERE Area = 'false'

--8)
SELECT L.TITULO
FROM BIBLIOTECA.LIBRO AS L
	JOIN BIBLIOTECA.LIBRO_EJEMPLAR AS LE
		ON L.CODIGO_LIBRO = LE.CODIGO_LIBRO
		 JOIN BIBLIOTECA.USUARIO_EJEMPLAR AS UE
			ON LE.CODIGO_EJEMPLAR = UE.CODIGO_EJEMPLAR
				JOIN BIBLIOTECA.USUARIO U
					ON U.CODIGO_USUARIO = UE.CODIGO_USUARIO
WHERE (U.NOMBRE='Andrew' and U.APELLIDOS = 'Molina Saenz')

--9)
SELECT TOP 1 [CODIGO_USUARIO]
, [NOMBRE]
, [APELLIDOS]
, [TELEFONO]
, [DIRECCION]
, [CARRERA]
, [LOCALIZACION]
, [edad]
FROM BIBLIOTECA.USUARIO
ORDER BY edad ASC

--10)
SELECT U.NOMBRE, L.[CODIGO_LIBRO], L.[TITULO], L.[ISBN], L.[PAGINAS], L.[EDITORIAL], L.[Area]
FROM BIBLIOTECA.USUARIO AS U
	JOIN BIBLIOTECA.USUARIO_EJEMPLAR AS UE
		ON U.CODIGO_USUARIO = UE.CODIGO_USUARIO
			JOIN BIBLIOTECA.LIBRO_EJEMPLAR AS LE
				ON UE.CODIGO_EJEMPLAR = LE.CODIGO_EJEMPLAR
					JOIN BIBLIOTECA.LIBRO AS L
						ON L.CODIGO_LIBRO = LE.CODIGO_LIBRO
WHERE (L.TITULO LIKE '%Bases de Datos%' OR L.TITULO LIKE '%SQL%' OR L.TITULO LIKE '%NoSQL%')
					
--11)
SELECT
[CODIGO_LIBRO]
, [TITULO]
, [ISBN]
, [PAGINAS]
, [EDITORIAL]
, [Area]
FROM BIBLIOTECA.LIBRO
WHERE EDITORIAL = 'Alfa y Omega'

--12)
SELECT L.TITULO
FROM BIBLIOTECA.LIBRO AS L
	JOIN BIBLIOTECA.AUTOR_LIBRO AS AL
		ON L.CODIGO_LIBRO= AL.CODIGO_LIBRO
			JOIN BIBLIOTECA.AUTOR AS A
				ON A.CODIGO= AL.CODIGO_AUTOR
WHERE A.NOMBRE = 'Mario Benedetti'

--13)
SELECT L.TITULO
FROM BIBLIOTECA.LIBRO AS L
	JOIN BIBLIOTECA.LIBRO_EJEMPLAR AS LE
		ON L.CODIGO_LIBRO = LE.CODIGO_LIBRO
			JOIN BIBLIOTECA.USUARIO_EJEMPLAR AS UE
				ON LE.CODIGO_EJEMPLAR = UE.CODIGO_EJEMPLAR
WHERE UE.FECHA_DEVOLUCION = '2020-09-10'

--14)
SELECT SUM(edad) AS Suma_Edades
FROM BIBLIOTECA.USUARIO

--15)
SELECT  [CODIGO_USUARIO]
, [NOMBRE]
, [APELLIDOS]
, [TELEFONO]
, [DIRECCION]
, [CARRERA]
, [LOCALIZACION]
, [edad]
FROM BIBLIOTECA.USUARIO
WHERE EDAD> (SELECT AVG(EDAD) AS PROMEDIO_EDAD FROM BIBLIOTECA.USUARIO)

--16)
declare @nombre_autor varchar(30)
set @nombre_autor = 'Julio Verne'

SELECT L.TITULO
FROM BIBLIOTECA.LIBRO AS L
	JOIN BIBLIOTECA.AUTOR_LIBRO AS AL
		ON L.CODIGO_LIBRO= AL.CODIGO_LIBRO
			JOIN BIBLIOTECA.AUTOR AS A
				ON A.CODIGO= AL.CODIGO_AUTOR
WHERE (A.NOMBRE = @nombre_autor)

--17)
INSERT INTO BIBLIOTECA.USUARIO
(
[CODIGO_USUARIO]
,[NOMBRE]
, [APELLIDOS]
, [TELEFONO]
, [DIRECCION]
, [CARRERA]
, [LOCALIZACION]
, [edad]
)
VALUES
(
1234
,'Juan'
,'De la mar'
,65421398
,'Cartago'
,6
,21
)

--18)
UPDATE [BIBLIOTECA].[LIBRO]
SET TITULO = 'El Padrino'
WHERE CODIGO_LIBRO = 3

--19)
SELECT L.[CODIGO_LIBRO]
, L.[TITULO]
, L.[ISBN]
, L.[PAGINAS]
, L.[EDITORIAL]
, L.[Area]
,U.NOMBRE
,U.CARRERA
,UE.FECHA_DEVOLUCION
FROM [BIBLIOTECA].[LIBRO] AS L
	JOIN BIBLIOTECA.LIBRO_EJEMPLAR AS LE
		ON L.CODIGO_LIBRO = LE.CODIGO_LIBRO
			JOIN BIBLIOTECA.USUARIO_EJEMPLAR AS UE
				ON LE.CODIGO_EJEMPLAR = UE.CODIGO_EJEMPLAR
					JOIN BIBLIOTECA.USUARIO AS U
						ON U.CODIGO_USUARIO = UE.CODIGO_USUARIO
WHERE (U.CARRERA='Matematica' AND UE.FECHA_DEVOLUCION <= '2020-09-01')

--20)
SELECT L.TITULO, A.NOMBRE, COUNT(LE.CODIGO_LIBRO) AS CANTIDAD,LO.RECINTO
FROM BIBLIOTECA.LIBRO AS L
	JOIN BIBLIOTECA.AUTOR_LIBRO AS AL
		ON L.CODIGO_LIBRO= AL.CODIGO_LIBRO
			JOIN BIBLIOTECA.AUTOR AS A
				ON A.CODIGO= AL.CODIGO_AUTOR
					JOIN BIBLIOTECA.LIBRO_EJEMPLAR LE
						ON LE.CODIGO_LIBRO = L.CODIGO_LIBRO
							JOIN BIBLIOTECA.EJEMPLAR AS E
								ON E.CODIGO_EJEMPLAR = LE.CODIGO_EJEMPLAR
									JOIN BIBLIOTECA.LOCALIZACION AS LO
										ON LO.ID_LOCALIZACION = E.LOCALIZACION
GROUP BY L.TITULO,A.NOMBRE,LE.CODIGO_LIBRO,LO.RECINTO

--21)
SELECT COUNT(CODIGO_LIBRO) AS CANTIDAD_LIBROS
FROM BIBLIOTECA.LIBRO

--22)
SELECT [CODIGO_USUARIO]
, [NOMBRE], [APELLIDOS]
, [TELEFONO]
, [DIRECCION]
, [CARRERA]
, [LOCALIZACION]
, [edad]
FROM BIBLIOTECA.USUARIO AS U
WHERE U.CODIGO_USUARIO NOT IN (SELECT UE.CODIGO_USUARIO		
                       FROM BIBLIOTECA.USUARIO_EJEMPLAR AS UE)

--23)
SELECT TITULO,PAGINAS, CASE
 WHEN PAGINAS>1000  
               THEN 'Libro extenso' 
 WHEN PAGINAS BETWEEN 500 AND 1000
			   THEN 'Libro regular'
 WHEN PAGINAS<500
			   THEN 'Libro pequeño'
       END AS EXTENSION
FROM [BIBLIOTECA].[LIBRO]


