--1)
SELECT JUE.N_SOCIO_JUGADOR,PAR.NOMBRE, PAI.NOMBRE_PAIS,JUE.NIVEL,PA.COD_PARTIDA,PA.JORNADA AS FECHA_DE_PARTIDA
FROM PRAC1.PARTIDA AS PA
	JOIN PRAC1.JUEGA AS JU
		ON PA.COD_PARTIDA = JU.COD_PARTIDA
			JOIN PRAC1.JUGADOR AS JUE
				ON JU.N_SOCIO_JUGADOR = JUE.N_SOCIO_JUGADOR
				JOIN PRAC1.PARTICIPANTE AS PAR
					ON JUE.N_SOCIO_JUGADOR = PAR.N_SOCIO
						JOIN PRAC1.PAIS AS PAI
							ON PAR.COD_PAIS = PAI.COD_PAIS
WHERE JORNADA='2020-03-01'

--2)
SELECT HO.[NOMBRE_HOTEL], [DIRECCION], [TELEFONO], SA.COD_SALA
FROM PRAC1.HOTEL AS HO
	JOIN PRAC1.SALA AS SA
		ON HO.NOMBRE_HOTEL= SA.NOMBRE_HOTEL
			LEFT JOIN  PRAC1.PARTIDA AS PA
				ON SA.COD_SALA = PA.COD_SALA
WHERE PA.COD_PARTIDA IS NULL


--3)

