USE IF4100

CREATE SCHEMA BIBLIOTECA

--CREATE TABLE BIBLIOTECA.AUTOR 
--(
--CODIGO INT PRIMARY KEY NOT NULL --MANERA 1--
--, NOMBRE VARCHAR(30) NOT NULL
--)

--CREATE TABLE BIBLIOTECA.LIBRO
--(
--CODIGO_LIBRO INT PRIMARY KEY
--, TITULO VARCHAR(50) NOT NULL
--,ISBN  VARCHAR(15) NOT NULL
--,PAGINAS INT NOT NULL
--,EDITORIAL VARCHAR (25)
--)

--CREATE TABLE BIBLIOTECA.AUTOR_LIBRO
--(
--CODIGO_AUTOR INT NOT NULL
--,CODIGO_LIBRO INT NOT NULL
----,PRIMARY KEY(CODIGO_AUTOR, CODIGO_LIBRO)-- MANERA 2---
--,CONSTRAINT PK_AUTOR_LIBRO PRIMARY KEY(CODIGO_AUTOR,CODIGO_LIBRO) --MANERA 3--
--, FOREIGN KEY (CODIGO_AUTOR) REFERENCES BIBLIOTECA.AUTOR(CODIGO)
--,FOREIGN KEY (CODIGO_LIBRO) REFERENCES  BIBLIOTECA.LIBRO(CODIGO_LIBRO)
--)

CREATE TABLE BIBLIOTECA.EJEMPLAR
(
 CODIGO       INT PRIMARY KEY  NOT NULL
,LOCALIZACION VARCHAR (20) NOT NULL
)

CREATE TABLE BIBLIOTECA.LIBRO_EJEMPLAR
(
 CODIGO_LIBRO    INT NOT NULL
,CODIGO_EJEMPLAR INT NOT NULL
 CONSTRAINT PK_LIBRO_EJEMPLAR PRIMARY KEY (CODIGO_LIBRO,CODIGO_EJEMPLAR) 
,FOREIGN KEY (CODIGO_LIBRO) REFERENCES BIBLIOTECA.LIBRO(CODIGO_LIBRO)
,FOREIGN KEY (CODIGO_EJEMPLAR) REFERENCES BIBLIOTECA.EJEMPLAR(CODIGO_EJEMPLAR)
)

CREATE TABLE BIBLIOTECA.USUARIO
(
 CODIGO_USUARIO INT PRIMARY KEY NOT NULL
,NOMBRE         VARCHAR(20) NOT NULL
,APELLIDOS      VARCHAR(40) NOT NULL
,TELEFONO       VARCHAR(10) NULL
,DIRECCION      VARCHAR(100)NOT NULL
,CARRERA        VARCHAR(40) NOT NULL
)

CREATE TABLE BIBLIOTECA.USUARIO_EJEMPLAR
(
  CODIGO_USUARIO  INT NOT NULL
 ,CODIGO_EJEMPLAR INT NOT NULL
 ,FECHA_PRESTAMO  DATETIME NOT NULL
 ,FECHA_DEVOLUCION DATE NOT NULL
 ,CONSTRAINT PK_USUARIO_EJEMPLAR PRIMARY KEY (CODIGO_USUARIO,CODIGO_EJEMPLAR)
 ,FOREIGN KEY (CODIGO_EJEMPLAR) REFERENCES BIBLIOTECA.EJEMPLAR(CODIGO_EJEMPLAR)
 ,FOREIGN KEY (CODIGO_USUARIO)  REFERENCES BIBLIOTECA.USUARIO(CODIGO_USUARIO)
)