SELECT * FROM [BIBLIOTECA].[USUARIO]
SELECT * FROM [BIBLIOTECA].[LIBRO]

-- A)--
--Profe 5 es igual a San Pedro--
SELECT  [NOMBRE], [DIRECCION]
FROM [BIBLIOTECA].[USUARIO]
WHERE ([LOCALIZACION]=5) AND ([DIRECCION] LIKE '%Cartago%')

-- B)--
SELECT DISTINCT [TITULO], [PAGINAS] FROM [BIBLIOTECA].[LIBRO]
WHERE ([EDITORIAL]='Ediciones Perro Azul') AND ([TITULO] LIKE '%O%')
ORDER BY [PAGINAS] ASC

--C)
SELECT TOP 3 [NOMBRE] 
FROM [BIBLIOTECA].[AUTOR]
WHERE [NOMBRE] = 'Paul Young'

INSERT INTO [BIBLIOTECA].[USUARIO] 
(
[CODIGO_USUARIO], [NOMBRE], [APELLIDOS], [TELEFONO], [DIRECCION], [CARRERA], [LOCALIZACION]
)
VALUES
(
15,'Fabian','Castro',65324189,'Cartago Centro','Informatica Empresarial',5
)

INSERT INTO [BIBLIOTECA].[AUTOR]
(
[CODIGO], [NOMBRE]
)

VALUES
(
4,'Pablo Escobar'
)


UPDATE [BIBLIOTECA].[LIBRO]
SET [PAGINAS] = 590
WHERE [TITULO] = 'El Androide'